[project]
name = "pyrogyro"
version = "0.0.2"
description = "Yet Another (Gyro) Gamepad Mapper, written in Python for hackability"
authors = [{ name = "ForOhForError" }]
requires-python = ">=3.11,<3.14"
readme = "README.md"
dependencies = [
    "pysdl3>=0.9, <0.10",
    "vgamepad>=0.1.0,<0.2",
    "pyautogui>=0.9.54,<0.10",
    "flask>=3.1.0,<4",
    "flask-sock>=0.7.0,<0.8",
    "pydantic>=2.10.6,<3",
    "ruamel-yaml>=0.18.10,<0.19",
    "psutil>=6.1.1,<7",
    "pydirectinput>=1.0.4,<2",
    "libevdev>=0.12 ; sys_platform == 'linux'",
]

[project.scripts]
pyrogyro = "pyrogyro.pyrogyro:appmain"
dist = "pyrogyro.project_util:build_windows_dist"
gen-configs = "pyrogyro.mapping:generate_default_mapping_files"

[dependency-groups]
dev = [
    "pyinstaller>=6.11.1,<7"
]

[tool.hatch.build.targets.sdist]
include = ["pyrogyro"]

[tool.hatch.build.targets.wheel]
include = ["pyrogyro"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
reportInvalidTypeForm = false
