name = "Default Xbox Controller"
autoload = true
autoload_exe_name = ".*"
autoload_window_name = ".*"

[ pad ]
# match_controller_name = ".*" # Regex for controller name, defaults to accepting anything
# multi_pad_mode = "duplicate" # Determines how to handle multiple pads
TYPE = "PAD"
N = "xbox.Y"
S = "xbox.A"
E = "xbox.B"
W = "xbox.X"
UP = "xbox.UP"
DOWN = "xbox.DOWN"
LEFT = "xbox.LEFT"
RIGHT = "xbox.RIGHT"
BACK = "xbox.BACK"
START = "xbox.START"
GUIDE = "xbox.GUIDE"
R1 = "xbox.R1"
R2 = "xbox.R2"
R3 = "xbox.R3"
L1 = "xbox.L1"
L2 = "xbox.L2"
L3 = "xbox.L3"
RSTICK = "xbox.RSTICK"
LSTICK = "xbox.LSTICK"

[ xbox ]
TYPE = "XBOX"
RUMBLE = "pad.RUMBLE"