name: Gyro On Explorer
autoload:
  match_exe_name: explorer.exe
  match_window_name: .*
  match_controller_name: .*
mapping:
  L2: RMOUSE
  R2: LMOUSE
  RSTICK: 
    map_as: AIM
    o: MOUSE
  GYRO: MOUSE
gyro:
  mode: 
    gyro_mode: PLAYER_TURN
    gyro_sens: 3
    fast_sens: [5, 4]
    slow_threshold: 5
    fast_threshold: 75
    smooth_window: 3
    smooth_threshold: 5
    tightening_theshold: 5
