name = "Default Xbox Controller"
autoload = true
autoload_exe_name = ".*"
autoload_window_name = ".*"

[ pad ]
# match_controller_name = ".*" # Regex for controller name, defaults to accepting anything
# multi_pad_mode = "duplicate" # Determines how to handle multiple pads
TYPE = "PAD"
N = "xbox.Y"
S = "xbox.A"
E = "xbox.B"
W = "xbox.X"
UP = "xbox.UP"
DOWN = "xbox.DOWN"
LEFT = "xbox.LEFT"
RIGHT = "xbox.RIGHT"
BACK = "xbox.BACK"
START = "xbox.START"
GUIDE = "xbox.GUIDE"
R1 = "xbox.R1"
R2 = "xbox.R2"
R3 = "xbox.R3"
L1 = "xbox.L1"
L2 = "xbox.L2"
L3 = "xbox.L3"
RSTICK = "xbox.RSTICK"
LSTICK = ["xbox.LSTICK","rumble_mult.IN"]
LP1 = "kb.F"
GYRO = "aim.GYRO"

[ xbox ]
TYPE = "XBOX"
RUMBLE = "pad.RUMBLE"

[ rumble_mult ]
TYPE = "MULT"
factor = 1.5
OUT = "pad.RUMBLE"

[ kb ]
TYPE = "KEYBOARD"

[ mouse ]
TYPE = "MOUSE"

[ aim ]
TYPE = "GYRO_TO_MOUSE"
MOUSE = "mouse.MOVE"
mode = "LOCAL"
real_world_calibration = 5.3333
sens = 3
fast_sens = [5, 4]
slow_threshold = 5
fast_threshold = 75
smooth_window = 0
smooth_threshold = 5
tightening_theshold = 5
