name: Default Mapping
mapping:
  NORTH: XUSB_GAMEPAD_Y
  SOUTH: XUSB_GAMEPAD_A
  EAST: XUSB_GAMEPAD_B
  WEST: XUSB_GAMEPAD_X
  BACK: XUSB_GAMEPAD_BACK
  START: XUSB_GAMEPAD_START
  DPAD_UP: XUSB_GAMEPAD_DPAD_UP
  DPAD_DOWN: XUSB_GAMEPAD_DPAD_DOWN
  DPAD_LEFT: XUSB_GAMEPAD_DPAD_LEFT
  DPAD_RIGHT: XUSB_GAMEPAD_DPAD_RIGHT
  LEFT_SHOULDER: XUSB_GAMEPAD_LEFT_SHOULDER
  RIGHT_SHOULDER: XUSB_GAMEPAD_RIGHT_SHOULDER
  LEFT_STICK: XUSB_GAMEPAD_LEFT_THUMB
  RIGHT_STICK: XUSB_GAMEPAD_RIGHT_THUMB
  GUIDE: XUSB_GAMEPAD_GUIDE
