name: Default Mapping
mapping:
  N: XUSB_GAMEPAD_Y
  S: XUSB_GAMEPAD_A
  E: XUSB_GAMEPAD_B
  W: XUSB_GAMEPAD_X
  BACK: XUSB_GAMEPAD_BACK
  START: XUSB_GAMEPAD_START
  UP: XUSB_GAMEPAD_DPAD_UP
  DOWN: XUSB_GAMEPAD_DPAD_DOWN
  LEFT: XUSB_GAMEPAD_DPAD_LEFT
  RIGHT: XUSB_GAMEPAD_DPAD_RIGHT
  L1: XUSB_GAMEPAD_LEFT_SHOULDER
  R1: XUSB_GAMEPAD_RIGHT_SHOULDER
  L3: XUSB_GAMEPAD_LEFT_THUMB
  R3: XUSB_GAMEPAD_RIGHT_THUMB
  GUIDE: XUSB_GAMEPAD_GUIDE
  L2: XUSB_GAMEPAD_L2
  R2: XUSB_GAMEPAD_R2
  LSTICK: XUSB_GAMEPAD_LSTICK
  RSTICK: XUSB_GAMEPAD_RSTICK
gyro:
  mode:
    gyro_mode: OFF
    gyro_sens: 1.0
  output:
