on:
  release:
    types: [created]

name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: windows-latest
    steps:
      - name: Make fake registry key for vigem bus
        shell: pwsh
        run: New-Item -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\ViGEMBus'
      - name: Make fake registry property for vigem bus
        shell: pwsh
        run: New-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\ViGEMBus' -Name 'Display Name' -PropertyType 'String' -Value 'nefarius virtual gamepad emulation bus driver' 
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install dependencies
        run: poetry install --with=dev
      - name: install vigembus
        shell: pwsh
        run: $path = Join-Path $(poetry env info --path) "Lib\site-packages\vgamepad\win\vigem\install\x64\ViGEmBusSetup_x64.msi"; Start-Process $path /passive -Wait
      - name: Build
        run: poetry run dist
      #- name: Upload the artifacts
      #  uses: skx/github-action-publish-binaries@master
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    releaseId: ${{ needs.create_release.outputs.id }}
      #    args: 'dist/*.exe'